[package]
name = "kayle_innate"
version = "0.0.5"
authors = ["j-mendez"]
edition = "2018"
license = "MIT"
description = "Incredibly fast and precise universal web accessibility evaluator for puppeteer or playwright."
repository = "https://github.com/a11ywatch/kayle"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
select = "0.6.0"
url = "2.3.1"
lazy_static = "1.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s"
