[workspace]
resolver = "2"
members = [
  "kayle_innate",
  "kayle_victor/victor",
  "kayle_scraper"
]

[workspace.dependencies]
smallvec = "1"
selectors = "0.21.0"
cssparser = "0.25.0"
html5ever = "0.26"
ego-tree = "0.6.2"
lazy_static = "1.4"
