name: Bench Compare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - node-version: 14.x
          - node-version: 16.x
          - node-version: 19.x
          - node-version: latest

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install and build locales
        run: yarn --no-immutable && ./build.sh

      - name: Run Bench compare a11y.js Playwright fast_axecore vs @axe-core/playwright
        run: cd ./a11y-js && yarn bench:playwright:axe

      - name: Run Bench compare a11y.js vs pa11y
        run: cd ./a11y-js && yarn bench:puppeteer:pa11y