name: Bench Compare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: 18.x
          - node-version: latest

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Wasm pack build modules
        run: cd kayle_innate && wasm-pack build --release --target nodejs kayle_innate && cd ../

      - name: Install and build locales
        run: yarn --no-immutable && yarn build && npx playwright install --with-deps chromium

      - name: Run Bench playwright fast_axecore
        run: cd ./kayle && yarn bench:playwright:axe

      - name: Run Bench playwright fast_htmlcs
        run: cd ./kayle && yarn bench:playwright:htmlcs