name: Performance Regression

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - node-version: 14.x
          - node-version: 16.x
          - node-version: 19.x
          - node-version: latest

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Wasm pack build modules
        run: cd kayle_innate && wasm-pack build --target nodejs && cd ../

      - name: Install and build locales
        run: yarn --no-immutable && yarn build

      - name: Run Bench fast_htmlcs
        run: cd ./kayle && yarn bench:playwright:htmlcs > output.json

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: kayle/output.json
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true