name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: 14.x
          - node-version: 16.x
          - node-version: 19.x

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: npm ci && npm run prepare
      - name: Run tests
        run: npm test
