name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - node-version: 14.x
          - node-version: 16.x
          - node-version: 19.x

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Wasm pack build modules
        run: cd kayle_innate && wasm-pack build --target nodejs && cd ../

      - name: Install and build locales
        run: npx playwright install && yarn --no-immutable && yarn build

      - name: Run Playwright kayle.js
        run: cd ./kayle && yarn test:playwright && yarn test:playwright:axe

      - name: Run Puppeteer kayle.js
        run: cd ./kayle && yarn test:puppeteer && yarn test:puppeteer:axe

      - name: Run Puppeteer [wasm] links handle
        run: cd ./kayle && yarn test:puppeteer:wasm