name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - node-version: 14.x
          - node-version: 16.x
          - node-version: 19.x

    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install and build locales
        run: yarn --no-immutable && yarn build

      # - name: Run Tests fast_axecore
      #   run: cd ./fast_axecore && yarn test 

      # - name: Run Tests fast_htmlcs
      #   run: cd ./fast_htmlcs && yarn test 

      - name: Run Playwright a11y.js
        run: cd ./a11y-js && yarn test:playwright && yarn test:playwright:axe

      - name: Run Puppeteer a11y.js
        run: cd ./a11y-js && yarn test:puppeteer && yarn test:puppeteer:axe